### PR TITLE
Changed variablename of only ID and made it clearer

### PR DESCRIPTION
**Pull request by Moburger**
Added userID to post entity

### CODE REVIEW

**Review by eric-muhire — CHANGES_REQUESTED** [review]
delete or updated beach by Id can not be changed to --> delete or update beachId due to naming conflict  in post entity.

**Review by MousaabYedjour — CHANGES_REQUESTED** [review]
Fix it

**Review by eric-muhire — APPROVED** [review]
ok, changes have been made

**Review by MousaabYedjour — APPROVED** [review]
Approuved

**Pull request merged**
